title: Rihen Mistry, MBA (Indian Institute of Management, Raipur)  # your name (or website title) here
logo: "/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Consultant
  <br><br>
  <a href="mailto:21pgp139@iimraipur.ac.in">21pgp139@iimraipur.ac.in </a>
  <br><br>
  <a href="https://www.linkedin.com/in/rihen-mistry-8225aa158/">LinkedIn </a>
  <br>
theme: jekyll-theme-minimal
